[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "envsnap"
version = "0.1.0"
description = "Capture, version and replay your dev environment like Git"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Chetan Kala", email = "kcheta99@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "click",
    "rich",
]
keywords = ["environment", "snapshot", "devtools", "cli", "versioning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Systems Administration",
]

[project.urls]
Homepage = "https://github.com/C-KALA/envsnap"
Repository = "https://github.com/C-KALA/envsnap"
"Bug Tracker" = "https://github.com/C-KALA/envsnap/issues"

[project.scripts]
envsnap = "envsnap.cli:main"
